channel: stable
addons:
  rs485-pool-controller:
    repository: hassio-addons/tree/master/rs485-pool-controller
    target: rs485-pool-controller
    image: hassioaddons/rs485-pool-controller-{arch}
  radiora-classic-bridge:
    repository: hassio-addons/tree/master/radiora-classic-bridge
    target: radiora-classic-bridge
    image: hassioaddons/radiora-classic-bridge-{arch}
  virtual-ip2sl:
    repository: hassio-addons/tree/master/virtual-ip2sl
    target: virtual-ip2sl
    image: hassioaddons/virtual-ip2sl-{arch}
  xantech-serial-bridge:
    repository: hassio-addons/tree/master/xantech-serial-bridge
    target: xantech-serial-bridge
    image: hassioaddons/xantech-serial-bridge-{arch}


