# IDEAL MINIMAL SETUP:

bridge:
  amplifiers:
    - type: xantech8
      tty: /dev/ttyUSB0

Minimal example with multiple matrix systems:

bridge:
  amplifiers:
    - type: xantech8
      tty: /dev/ttyUSB0
    - type: monoprice6
      tty: /dev/ttyUSB1
    - type: xantech8
      name: "
      tty: /dev/ttyUSB2  # NOTE: could be a remote iTach Flex WiFi/IP endpoint

bridge:
  port: xxxx # optional, default 5000
  host: xxxx # optional
  auth: # optional, authentation not yet defined

  amplifiers:
    - type: xantech8
      tty: /dev/ttyUSB0
      amp: xantech1 # optional slug to identify this amp, determines the amp slug, defaults to type value (plus numeric suffix if multiple)

    - type: xantech8
      tty: /dev/ttyUSB1
      name: "Second Floor Xantech"

      zones: 
        - id: 1
	  name: Master Bedroom # optional
	  slug: master_bedroom # optional, defaults to whitespace converted to _
	  max_volume: 50 # optional
        - id: 2
	  name: Kitchen # optional
	- id: 3
	  name: Home Theater

      sources:
        - id: 1
	  name: "Sonos (Main)"
        - id: 2
	  name: "Sonos (Secondary)"
        - id: 3
	  name: "TV"
        - id: 4`<
	  name: "CD"
        - id: 5
	  name: "3.5mm Input"
        - id: 6
	  name: "CD"
