# IDEAL MINIMAL SETUP:

bridge:
  amplifiers:
    xantech:
      type: xantech8
      serial: /dev/ttyUSB0

Minimal example with multiple matrix systems:

bridge:
  amplifiers:
    xantech-upstairs:
      type: xantech8
      name: "Xantech Upstairs"
      tty: /dev/ttyUSB0
      serial: /dev/ttyUSB0
    monoprice:
      type: monoprice6
      tty: /dev/ttyUSB1
      serial: /dev/ttyUSB1
    xantech-basement:
      type: xantech8
      name: "Xantech Basement"
      tty: /dev/ttyUSB2  # NOTE: could be a remote iTach Flex WiFi/IP endpoint
      serial: /dev/ttyUSB3

bridge:
  port: xxxx # optional, default 5000
  host: xxxx # optional
  auth: # optional, authentation not yet defined

  amplifiers:
    - type: xantech8
      tty: /dev/ttyUSB0
      amp: xantech1 # optional slug to identify this amp, determines the amp slug, defaults to type value (plus numeric suffix if multiple)

    - type: xantech8
      serial: /dev/ttyUSB1
      tty: /dev/ttyUSB1
      name: "Second Floor Xantech"

      zones: 
        1:
	        name: Master Bedroom # optional
	        slug: master_bedroom # optional, defaults to whitespace converted to _
	        max_volume: 50 # optional
        2:
	        name: Kitchen # optional
	      3:
	        name: Home Theater

      sources:
        1:
	        name: "Sonos (Main)"
        2:
	        name: "Sonos (Secondary)"
        3:
	        name: "TV"
        4:
	        name: "CD"
        5:
	        name: "3.5mm Input"
        6:
	        name: "CD"


example_zones:
  - Atrium
  - Basement
  - Bathroom
  - Bedroom
  - Deck
  - Dinette
  - Dining Room
  - Dressing Room
  - Entrance
  - Family Room
  - Foyer
  - Game Room
  - Guest Suite
  - Gym
  - Hallway
  - Kids Room 1
  - Kids Room 2
  - Kitchen
  - Lanai
  - ibrary
  - Living Room
  - Loft
  - Master Bath
  - Master Bedroom
  - Master Suite
  - Media Room
  - Observatory
  - Office
  - Outside
  - Patio
  - Play Room
  - Pool Area
  - Powder Room
  - Sitting Room
  - Solarium
  - Theater

example_sources:
  - Auxiliary 1
  - Auxiliary 2
  - AM-FM
  - Apple TV
  - Blu-Ray
  - Cable
  - Computer
  - CD
  - DVD
  - DVR
  - FM
  - Game Console
  - iPod
  - Internet Radio
  - Media Player
  - Media System
  - Record Player
  - Sirius Radio
  - Streaming
  - TV
  - TiVo
  - VCR
  - XM Radio
