xantech8:
  name: "Xantech 8-Zone Audio"
  num_zones: 8
  num_sources: 8

  hardware_volume_steps: 38

  # NOTE: this was actually Monoprice's zone pattern
  protocol:
    zone_pattern: '#>(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)'
    eol: '\r\n#'
    
    serial_timeout :2
 
  protocol_supported:
    PO: true  # power (Xantech)
    PR: false # power (Monoprice/Dayton Audio)
    SS: true  # source select (Xantech)
    CH: false # source channel (Monoprice/Dayton Audio)
    VO: true  # volume
    MU: true  # mute
    TR: true  # treble
    BS: true  # bass
    BA: true  # balance
    LS: true  # linked keypad
    PS: true  # paged (Xantech)
    DT: false # do-not-disturb (Monoprice/Dayton Audio)
    PA: false # public-address-12v-control (Monoprice/Dayton Audio)
    IS: false # input line 1 or bus 0 (Monoprice/Dayton Audio)

# These are all Monoprice protocol details
  queries:
    prefix: '?'
    eol: ''

  commands:
    prefix: '!' 
    eol: '+'

    zone_status:   '?{}' #????

    power_on:      '!{zone}PR1'
    power_off:     '!{zone}PR0'

    mute_on:       '!{zone}MU1'
    mute_off:      '!{zone}MU0'

    volume_up:     '!{zone}VI'
    volume_down:   '!{zone}VD'
    set_volume:    '!{zone}VO{:02}' # zone / level 0-38

    source_select: '!{zone}SS{source}'

    balance_left:  '!{zone}BL'
    balance_right: '!{zone}BR'

    bass_up:       '!{zone}BI'
    bass_down:     '!{zone}BD'

    balance_left:  '!{zone}BL'
    balance_right: '!{zone}BR'

    treble_up:     '!{zone}TI'
    treble_down:   '!{zone}TD'

#    set_treble:  '<{zone}TR{:02}' # zone / level 0-14
#    set_bass:    '<{zone}BS{:02}' # zone / level 0-14
#    set_balance: '<{zone}BL{:02}' # zone / level 0-20
#    set_source:  '<{zone}CH{:02}' # zone / 0-6

  bass_level:
    unit: "dB"
    steps:
      - "14": "+14"
      - "13": "+12"
      - "12": "+10"
      - "11": "+8"
      - "10": "+6"
      -  "9": "+4"
      -  "8": "+2"
      -  "7": "0"
      -  "6": "-2"
      -  "5": "-4"
      -  "4": "-6"
      -  "3": "-8"
      -  "2": "-10"
      -  "1": "-12"
      -  "0": "-14"

  treble_level:
    unit: "dB"
    steps:
      - "14": "+14"
      - "13": "+12"
      - "12": "+10"
      - "11": "+8"
      - "10": "+6"
      -  "9": "+4"
      -  "8": "+2"
      -  "7":  "0"
      -  "6": "-2"
      -  "5": "-4"
      -  "4": "-6"
      -  "3": "-8"
      -  "2": "-10"
      -  "1": "-12"
      -  "0": "-14"
 
  balance_level:
    unit: Unknown
    steps:
      - "20": "left"
      - "19": "left"
      - "18": "left"
      - "17": "left"
      - "16": "left"
      - "15": "left"
      - "14": "left"
      - "13": "left"
      - "12": "left"
      - "11": "left"
      - "10": "left"
      -  "9": "left"
      -  "8": "left"
      -  "7": "left"
      -  "6": "left"
      -  "5": "left"
      -  "4": "left"
      -  "3": "left"
      -  "2": "left"
      -  "1": "left"
      -  "0": "left"

   # volume_level:
   # units: "dB"
   #  steps:

   switched:
      -  "on": "01" # FIXME: Monoprice is 2-digit, what about Xantech?
      - "off": "00"

   default_sources:
      - "1": "Sonos"
      - "2": "CD"
      - "3": "DVD"
      
