xantech8:
  name: "Xantech 8-Zone Audio"
  num_zones: 8
  num_sources: 8

  hardware_volume_steps: 38

  # NOTE: this was actually Monoprice's zone pattern
  protocol:
    zone_pattern: '#>(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)'
    eol: '\r\n#'
    
    serial_timeout :2
 
  protocol_supported:
    PO: true  # power (Xantech)
    PR: false # power (Monoprice/Dayton Audio)
    SS: true  # source select (Xantech)
    CH: false # source channel (Monoprice/Dayton Audio)
    VO: true  # volume
    MU: true  # mute
    TR: true  # treble
    BS: true  # bass
    BA: true  # balance
    LS: true  # linked keypad
    PS: true  # paged (Xantech)
    DT: false # do-not-disturb (Monoprice/Dayton Audio)
    PA: false # public-address-12v-control (Monoprice/Dayton Audio)
    IS: false # input line 1 or bus 0 (Monoprice/Dayton Audio)

# These are all Monoprice protocol details
  requests:
    zone_status: '?{}\r'
    set_power:   '<{}PR{}\r'    # zone / '01' or '00'
    set_mute:    '<{}MU{}\r'    # zone / '01' or '00'
    set_volume:  '<{}VO{:02}\r' # zone / 0-38
    set_treble:  '<{}TR{:02}\r' # zone / 0-14
    set_bass:    '<{}BS{:02}\r' # zone / 0-14
    set_balance: '<{}BL{:02}\r' # zone / 0-20
    set_source:  '<{}CH{:02}\r' # zone / 0-6

  bass_level:
    unit: dB
    steps:
      - "14": "+14"
      - "13": "+12"
      - "12": "+10"
      - "11": "+8"
      - "10": "+6"
      - "9": "+4"
      - "8": "+2"
      - "7": "0"
      - "6": "-2"
      - "5": "-4"
      - "4": "-6"
      - "3": "-8"
      - "2": "-10"
      - "1": "-12"
      - "0": "-14"

  treble_level:
    unit: dB
    steps:
      - "14": "+14"
      - "13": "+12"
      - "12": "+10"
      - "11": "+8"
      - "10": "+6"
      - "9": "+4"
      - "8": "+2"
      - "7": "0"
      - "6": "-2"
      - "5": "-4"
      - "4": "-6"
      - "3": "-8"
      - "2": "-10"
      - "1": "-12"
      - "0": "-14"
 
