xantech8:
  name: "Monoprice 6-Zone Audio"
  num_zones: 6
  num_sources: 6

  hardware_volume_steps: 38
  hardware_treble_steps: 14
  hardware_bass_steps: 14
  hardware_balance_steps: 20

  # NOTE: this was actually Monoprice's zone pattern
  protocol:
    zone_pattern: '#>(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)'
    eol: '\r\n#'
    serial_timeout :2


  # These are all Monoprice protocol details
  requests:
    eol: '\r'
    
    zone_status: '?{zone}'
    set_power:   '<{zone}PR{state}'    # zone / '01' or '00'
    set_mute:    '<{zone}MU{state}'    # zone / '01' or '00'
    set_volume:  '<{zone}VO{:02}' # zone / 0-38
    set_treble:  '<{zone}TR{:02}' # zone / 0-14
    set_bass:    '<{zone}BS{:02}' # zone / 0-14
    set_balance: '<{zone}BL{:02}' # zone / 0-20
    set_source:  '<{zone}CH{:02}' # zone / 0-6

  bass_level:
    unit: dB
    steps:
      - "14": "+14"
      - "13": "+12"
      - "12": "+10"
      - "11": "+8"
      - "10": "+6"
      - "9": "+4"
      - "8": "+2"
      - "7": "0"
      - "6": "-2"
      - "5": "-4"
      - "4": "-6"
      - "3": "-8"
      - "2": "-10"
      - "1": "-12"
      - "0": "-14"

  treble_level:
    unit: dB
    steps:
      - "14": "+14"
      - "13": "+12"
      - "12": "+10"
      - "11": "+8"
      - "10": "+6"
      - "9": "+4"
      - "8": "+2"
      - "7": "0"
      - "6": "-2"
      - "5": "-4"
      - "4": "-6"
      - "3": "-8"
      - "2": "-10"
      - "1": "-12"
      - "0": "-14"
 
