version: 1
formatters:
  simple:
    format: '%(asctime)s %(name)-12s %(levelname)-8s %(message)s'
  minimal:
    format: '%(levelname)-10s %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: minimal
    stream: ext://sys.stdout

  stderr:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stderr

  info_log:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: info.log
    encoding: utf8

loggers:
  simpleExample:
    level: DEBUG
    handlers: [console]
    propagate: no

root:
  level: DEBUG
  handlers: [console]
